name: Docker Build without Persistent Cache
run-name: build without persistent cache

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Docker image with cache
        run: |
          docker build \
            --target without_cache \
            -t your-image-name .