name: Install dependencies witht cache
run-name: Install dependencies with  cache
 
on: [push, pull_request]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Buildx
        uses: docker/setup-buildx-action@v2
        with:
          driver: docker-container

      - name: Restore Cache
        uses: actions/cache@v3
        id: docker-cache
        with:
          path: .cache/docker
          key: docker-cache-${{ github.sha }}
          restore-keys: |
            docker-cache-

      - name: Build Image
        uses: docker/build-push-action@v4
        with:
          context: tp_cache
          file: tp_cache/Dockerfile
          target: with_cache
          tags: image-with-cache
          cache-from: type=local,src=.cache/docker
          cache-to: type=local,mode=max,dest=.cache/docker