name: Install dependencies with pip cache
run-name: Install dependencies with pip cache

on: [push, pull_request]

jobs:
  install-dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache layer 
        uses: actions/cache@v3
        with:
          path: /tmp/docker-cache
          key: ${{ runner.os }}-pip-${{ hashFiles('tp_cache/requirements.txt', 'tp_cache/Dockerfile') }}
          restore-keys: |
            ${{ runner.os }}-docker-

      - name: load local image
        run:  docker buildx create --driver-opt default-load=true
 
      - name: Build Docker image
        run: run: docker buildx build \
            --cache-to type=local,mode=max,dest=/tmp/docker-cache \
            --cache-from type=local,src=/tmp/docker-cache \
            -t image-with-cache \
            --target with_cache .



