name: Install dependencies with pip cache
run-name: Install dependencies with pip cache

on: [push, pull_request]

jobs:
  install-dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python environment
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: 
            /home/runner/work/cache_advantage/cache_advantage/tp_cache/.env
          key: ${{ runner.os }}-pip-${{ hashFiles('tp_cache/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-


      - name: Install dependencies 
        run: |
          python -m venv .env
          source .env/bin/activate
          pip install -r requirements.txt
          pwd
        working-directory: tp_cache

      - name: Build Docker image
        run: |
          DOCKER_BUILDKIT=1 docker buildx build --target with_cache -t image-with-cache -f tp_cache/Dockerfile tp_cache
          docker run --rm -d -p 8000:8000 --name my_container image-with-cache 
          docker logs my_container
          sleep 15
          curl -f http://localhost:8000


