name: Install dependencies without pip cache
run-name: Install dependencies without pip cache
 
on: [push, pull_request]

jobs:
  install-dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: '3.11' 

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r tp_cache/requirements.txt 
