name: Install dependencies with pip cache
run-name: Install dependencies with pip cache

on: [push, pull_request]

jobs:
  install-dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache layer 
        uses: actions/cache@v3
        with:
          path: ~/.cache/docker
          key: ${{ runner.os }}-pip-${{ hashFiles('tp_cache/requirements.txt', 'tp_cache/Dockerfile') }}
          restore-keys: |
            ${{ runner.os }}-docker-

      - name: load local image
        run:  docker buildx create --driver-opt default-load=true
 
      - name: Build Docker image
        run: docker buildx build \
          --cache-to type=local,dest=~/.cache/docker \
          --cache-from type=local,src=~/.cache/docker \
          -t image-with-cache \
          --target with_cache .


