name: Install dependencies with pip cache
run-name: Install dependencies with pip cache

on: [push, pull_request]

jobs:
  install-dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache layer 
        uses: actions/cache@v3
        with:
          path: ~/.cache/docker
          key: ${{ runner.os }}-pip-${{ hashFiles('tp_cache/requirements.txt', 'tp_cache/Dockerfile') }}
          restore-keys: |
            ${{ runner.os }}-docker-


      - name: Build Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: false
          tags: my-image:latest
          cache-from: type=local,src=~/.cache/docker
          cache-to: type=local,mode=max,dest=~/.cache/docker 


