name: Install dependencies without pip cache
run-name: Install dependencies without pip cache
 
on: [push, pull_request]


jobs:
  install-dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      
      - name: Build Image
        uses: docker/build-push-action@v4
        with:
          context: tp_cache
          file: tp_cache/Dockerfile
          target: without_cache
          tags: image-without-cache