name: Docker Build with Pre-installed Dependencies Cache

on: [push, pull_request]

jobs:
  install-dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Restore pip cache
        id: pip-cache
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: pip-cache-${{ runner.os }}-${{ hashFiles('tp_cache/requirements.txt') }}
          restore-keys: |
            pip-cache-${{ runner.os }}-

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install --cache-dir ~/.cache/pip -r tp_cache/requirements.txt

  build-docker:
    runs-on: ubuntu-latest
    needs: install-dependencies
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Restore pip cache
        id: pip-cache
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: pip-cache-${{ runner.os }}-${{ hashFiles('tp_cache/requirements.txt') }}
          restore-keys: |
            pip-cache-${{ runner.os }}-

      - name: Build Docker image using cached dependencies
        env:
          DOCKER_BUILDKIT: 1
        run: |
          docker build \
            --build-arg PIP_CACHE_DIR=/root/.cache/pip \
            --target with_cache \
            -t with_cache \
            -f tp_cache/Dockerfile tp_cache
