name: Install dependencies with pip cache

on: [push, pull_request]

jobs:
  install-dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: '3.11' 

      - name: Restore pip cache
        id: pip-cache
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip  
          key: pip-cache-${{ runner.os }}-${{ hashFiles('tp_cache/requirements.txt') }}  # Clé basée sur requirements.txt
          restore-keys: |
            pip-cache-${{ runner.os }}-

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install --cache-dir ~/.cache/pip -r tp_cache/requirements.txt  # Utilisation de la cache pip pour installer les dépendances
