name: Install dependencies with pip cache
run-name: Install dependencies with pip cache

on: [push, pull_request]

jobs:
  install-dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python environment
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: /opt/.env
          key: ${{ runner.os }}-pip-${{ hashFiles('tp_cache/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-


      - name: Install dependencies 
        run: |
          python -m venv /opt/.env
          PATH="/opt/.env/bin:$PATH"
          pip install -r requirements.txt
        working-directory: tp_cache

      - name: Build Docker image
        run: DOCKER_BUILDKIT=1 docker buildx build --target with_cache -t image-with-cache -f tp_cache/Dockerfile tp_cache

