name: Docker Build with Persistent Cache
run-name: build with persistent cache

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker BuildKit
        run: echo "DOCKER_BUILDKIT=1" >> $GITHUB_ENV

      - name: Restore pip cache
        id: pip-cache
        uses: actions/cache@v4
        with:
          path: /tmp/pip-cache
          key: pip-cache-${{ runner.os }}-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            pip-cache-${{ runner.os }}-

      - name: Build Docker image with cache
        run: |
          docker build \
            --build-arg PIP_CACHE_DIR=/tmp/pip-cache \
            --target with_cache \
            -t your-image-name .